# Generated by Django 5.1.2 on 2024-10-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
